### ISSUE TITLE
为什么PGW module要分anchor based和anchor free ？

### ISSUE THREAD

**Issue by monsterlyg** [ChenhongyiYang/PGD#7]
从论文里面没有看出为何要区分分anchor based和anchor free。从论文上看，我的理解是一个gt box对应n个predictions，然后给gt box中的grid算quality q；从gt box中的grid里选择top k，mle估计均值和方差后，再对top k个grid计算权重。但是我看了代码有pgw_anchor_based和pgw_anchor_free的区分，没有理解，希望能收到作者答复

**Comment by ChenhongyiYang** [comment]
Hi,

Thank you for noticing our work. You are correct that In PGD there is no difference w.r.t. anchor_based or anchor_free detectors. I separated them because the implementation details of their label encoding are different. For example, anchor_free encoders take in points, and anchor_free encoders take in boxes. Therefore,  for convenience, I coded them separately.

TY!
Chenhongyi
